- name: Installing Docker
  ansible.builtin.shell:
    cmd: curl -fsSL https://get.docker.com/ | sh
    creates: /usr/bin/docker
  become: true

- name: Enabling Docker Service
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started
  become: true

- name: Updating Docker Permissions
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true
  become: true

- name: Downloading Docker Images
  community.docker.docker_image_pull:
    name: "{{ item }}"
  loop: "{{ docker }}"
  when: docker is defined and docker | length > 0
